### ISSUE TITLE
storr support

### ISSUE THREAD

**Issue by richfitz** [richfitz/thor#8]
Can probably go into this package without bloating things out too much

**Comment by wlandau-lilly** [comment]
What about the reverse direction? Will there be a [thor](https://github.com/richfitz/thor)-powered [storr](https://github.com/richfitz/storr) driver at some point?

**Comment by richfitz** [comment]
That is what this issue is for

**Comment by richfitz** [comment]
storr support up on master now - turns out I did this a while ago.

A very quick benchmark suggests for simple access it should be ~2x as fast as rds
